<?
if (!defined('INC_DIR')) define('INC_DIR',dirname(__FILE__));
require_once(INC_DIR."/basefunction.inc");
require_once(INC_DIR."/logon.inc");
require_once(INC_DIR.'/dh.php'); 
require_once(INC_DIR.'/initdrv.php');

?>
<html>
<head>
<title>Walter's Information Center</title>
<meta http-equiv="content-type" content="text/html; charset=gb2312">
<link rel="stylesheet" href="<?=$basepath?>/style/styles.css" type="text/css">
<script language=javascript src="<?=$basepath?>/script/functions.js"></script>
</head>
<body bgcolor=#ffffff  link=#0066cc vlink=#0066cc alink=#9900ff  leftmargin=10 topmargin=10 marginheight=10 marginwidth=10>